<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>JitDalshe.Infrastructure.Notifications</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Application\JitDalshe.Application\JitDalshe.Application.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Extensions.Hosting.AsyncInitialization" Version="3.0.1"/>
        <PackageReference Include="Telegram.Bot" Version="22.6.0"/>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.7"/>
    </ItemGroup>

</Project>
