// <auto-generated />
using System;
using JitDalshe.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JitDalshe.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PostgresqlDbContext))]
    [Migration("20250413093427_AddNewsTables")]
    partial class AddNewsTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JitDalse.Domain.Entities.News", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("ExtId")
                        .HasColumnType("bigint")
                        .HasColumnName("ext_id");

                    b.Property<DateOnly>("PublicationDate")
                        .HasColumnType("date")
                        .HasColumnName("publication_date");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ExtId")
                        .IsUnique();

                    b.ToTable("news", (string)null);
                });

            modelBuilder.Entity("JitDalse.Domain.Entities.NewsPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("ExtId")
                        .HasColumnType("bigint")
                        .HasColumnName("ext_id");

                    b.Property<Guid>("NewsId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uri");

                    b.HasKey("Id");

                    b.HasIndex("ExtId")
                        .IsUnique();

                    b.HasIndex("NewsId");

                    b.ToTable("news_photo", (string)null);
                });

            modelBuilder.Entity("JitDalse.Domain.Entities.NewsPrimaryPhoto", b =>
                {
                    b.Property<Guid>("NewsId")
                        .HasColumnType("uuid")
                        .HasColumnName("news_id");

                    b.Property<Guid>("NewsPhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("news_photo_id");

                    b.HasKey("NewsId", "NewsPhotoId");

                    b.HasIndex("NewsId")
                        .IsUnique();

                    b.HasIndex("NewsPhotoId")
                        .IsUnique();

                    b.ToTable("news_primary_photo", (string)null);
                });

            modelBuilder.Entity("JitDalse.Domain.Entities.NewsPhoto", b =>
                {
                    b.HasOne("JitDalse.Domain.Entities.News", "News")
                        .WithMany("Photos")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("News");
                });

            modelBuilder.Entity("JitDalse.Domain.Entities.NewsPrimaryPhoto", b =>
                {
                    b.HasOne("JitDalse.Domain.Entities.News", "News")
                        .WithOne("PrimaryPhoto")
                        .HasForeignKey("JitDalse.Domain.Entities.NewsPrimaryPhoto", "NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JitDalse.Domain.Entities.NewsPhoto", "NewsPhoto")
                        .WithOne("PrimaryPhoto")
                        .HasForeignKey("JitDalse.Domain.Entities.NewsPrimaryPhoto", "NewsPhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("News");

                    b.Navigation("NewsPhoto");
                });

            modelBuilder.Entity("JitDalse.Domain.Entities.News", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("PrimaryPhoto");
                });

            modelBuilder.Entity("JitDalse.Domain.Entities.NewsPhoto", b =>
                {
                    b.Navigation("PrimaryPhoto");
                });
#pragma warning restore 612, 618
        }
    }
}
